# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd7273ead04b7d26cbb90c4a909213592fb7cd28855b79788b99f0ca81c0655d0c65866521cc4b2466362c84b469ca9c3b239bf6e5a2ceb86c8b9218cd4afa82

test:
  secret_key_base: 531dfc63dae845844d8e34c4b5a2f5b4f39ffa665e21be117cbccf365ce9766d463cdf0d348a710dd16b31f0278dbc98e31724d07ad1aa7a5ba82f79612af426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
